[connections.gsheets]
type = "service_account"
project_id = "project-polymer-program"
private_key_id ="64313c671faeb5fc5dae0b2f01d395e19e04734c"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCMvl4yHj5YM6g+\nwwJUfsWde4e2HapOneXZ6R+7Z1+KB9LHG+z8YQKQGgF3q1TYcLRbuUcFiuwKotRV\nysSs4eUNtqkmJlNcCOgZSRpGbe+zJCA37QyN6fjh5D9FLquQh5m5Do8+Sl52yQ2Z\nhoeiu+rnJ/U/+mlPt9LwDFvYr2DAE16EFBWveSSXwQTjjuTH/zGjhU/4RiShEhu2\nAJ32huTXYeYrpTWmbDRY8deJCpA2L4zkjx0FsUWbh5X8E+SZes/75gfnU46n/RXp\n/SWeDQ3+28DGzaMDmy1CpQBsGiEYhzNQqmLn7sXfHsB5dXalCOiDghzTJbt8IY9j\nAODctEQNAgMBAAECggEAF2rYQOYD0QidSn4HXfgu2K5UTQKgEs8WTpzJfRSs0opN\nMXhNxMs+UiwliNv+tLmB5M4NyVgNQJLJmhGwCiTWx+KXv8N6NLK9rXFamBPUIV4W\nJz//igA/OxSPS2tBu/034FDSGBbnI0P+CYiW+kZihf4Bwhif25X2GJ8xy/qYMjT3\nmoIBhQXGzyZlItKJ2uwVwEF/YfNmtPb8wn8Fjp5BfYMWK7Du3/5EQiGaMcyH8TXj\nn4KFiSd/1QdyVxDqf3e2pQQZVj4q4FO7Zfu6JZNNIkvzJ8GOdelllaJxf0ZY4daA\nE2z3j5vIQ7bEJ9+Z9yFAYLVb/7c8gqubm1iGnx+l2QKBgQDFg49JvrbcoMZUAcT/\nt6PiMbzRmgodDvkv0giyProhwdMOMiR0jaL1p/QiIMlKG1KP2rw0n39ux3G3IY2B\nUXbghMquPC3JbrOZKz3bKED/ZcyWSRPyTzdumVTzB6n1PkmmU2N2vSdxc5n7kD3n\nsErZf1IzwwMTToI1e/vjyGRm9QKBgQC2a13CbPsfgnUriGzGTdCykwbZ9BOBId9Q\nrZJAg4/WIqyLMrJRmBlZQhIqyIL4A7UBR0KO0XjvGOPlkVjDtFVr9vgUU6p7yx/J\nZIoZuHGiz/Ja19xTWslskrEfADrZ5UECf/GQ526zbQy+4sc8cLzHawXgLNkjlnNj\nw43iXWJJuQKBgQC0WCu9aiYNzb9JdVQrKcK6BjAiMkSJw+JDh8Po/N13dUMA80fW\nJH1nULPZdZZV1BzOvSqb4ga5X+K1FC3gpkGlP5rQ/KHSCwJyGMmiEl9G0+y6TH+q\nACrdEaQ/RAArrXQSKpHnGU+qh6NRz6K2qoGtllO4b5efSVAbBdo5YgBLAQKBgQCU\nJ7E3lmGCnubg22VUzaBhWG4pGEW7DDKeCMqOoQtyJCk0yJDxGfIEf1fX7ZAJNKGO\njzysV867ieCV860/DTiPfj7P63+8GSYQ4BoVd6q7S96PD2A/Rq3vA1jdT8d8buiU\nyir8wCo1iazfX7nnCb0YzYAxKNuWPrwq24lhvuxz6QKBgATD6/JrCn0HDMSthzi0\nfJnOu6WF0k+M44LD8LveqbMbjOX0z0AMXHmTAR9Ba4VA4HHINPykxcesKsaqArJ1\n4ODuShCwr3m0sr/AS8sQ9Y1LRdCc+MHGPwqIlv5ho/V50HFd9PiUpW1j1EGWYmnc\nRVkywt4CFQDL2uHFzY73nO7E\n-----END PRIVATE KEY-----\n"
client_email = "service-acc@project-polymer-program.iam.gserviceaccount.com"
client_id = "109383878974076697249"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/service-acc%40project-polymer-program.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[file_address]
JSON_FILE_ID = "1lW8O7d-jdrp0WiRg3Uwm7qfkGrQvY7uD"
SPREADSHEET_URL = "https://docs.google.com/spreadsheets/d/18sGa7-DQ0v0oHpMesTySUjr9Z4dh70hr4PUNm6t3uo0/"
WORKSHEET_SALES = "RawSales"
WORKSHEET_CMR = "CMRData"
WORKSHEET_GROUP = "CustGroup"
WORKSHEET_MOU = "MOUData"

[passwords]
admin = "zGjhU$78u"
user1 = "4RiS$hEhu2"